FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /srv

RUN pip install --no-cache-dir uv

COPY pyproject.toml ./
RUN uv pip install --system --no-cache .

COPY alembic.ini ./
COPY migrations ./migrations
COPY app ./app

EXPOSE 8080

CMD ["uvicorn", "app.web.app:app", "--host", "0.0.0.0", "--port", "8080"]
